name: finetune
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python=3.11
  - ipykernel
  - pytorch
  - pytorch-cuda=11.8
  - torchaudio
  - torchvision
  - pip
  - pip:
    - PyPDF2
    - python-docx
    - pywin32
prefix: C:\ProgramData\anaconda3\envs\finetune
